# Generated by Django 5.1.2 on 2025-05-31 12:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sn",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("paper", models.UUIDField(verbose_name="论文的uuid")),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                ("email", models.CharField(max_length=20, verbose_name="邮箱")),
                ("phone", models.CharField(max_length=20, verbose_name="手机号")),
            ],
            options={
                "verbose_name": "作者",
                "verbose_name_plural": "作者",
                "db_table": "author",
            },
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sn",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("number", models.CharField(max_length=50, verbose_name="论文编号")),
                ("title", models.CharField(max_length=200, verbose_name="论文标题")),
                ("journal", models.CharField(max_length=100, verbose_name="期刊名称")),
                ("publish_date", models.DateField(verbose_name="发表日期")),
                ("abstract", models.TextField(verbose_name="摘要")),
                ("keywords", models.CharField(max_length=200, verbose_name="关键词")),
                ("file", models.CharField(max_length=255, verbose_name="论文文件")),
                ("applicant_sn", models.UUIDField(verbose_name="申请人标识")),
                (
                    "applicant_name",
                    models.CharField(max_length=50, verbose_name="申请人姓名"),
                ),
                (
                    "applicant_email",
                    models.CharField(max_length=50, verbose_name="申请人邮箱"),
                ),
            ],
            options={
                "verbose_name": "论文",
                "verbose_name_plural": "论文",
                "db_table": "paper",
            },
        ),
    ]
