# Generated by Django 5.1.3 on 2025-04-07 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sn",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("date", models.DateField(verbose_name="比赛日期")),
                ("description", models.CharField(max_length=255, verbose_name="比赛描述")),
                ("score", models.CharField(max_length=100, verbose_name="比赛成绩")),
                ("teacher", models.CharField(max_length=50, verbose_name="带队老师")),
                ("team_id", models.CharField(max_length=100, verbose_name="团队的uuid")),
                (
                    "file",
                    models.FileField(upload_to="competitions/", verbose_name="证书图片"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待确认"), ("confirmed", "已确认")],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "比赛",
                "verbose_name_plural": "比赛",
                "db_table": "competition",
            },
        ),
        migrations.CreateModel(
            name="CompetitionMemberConfirm",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("student", models.CharField(max_length=100, verbose_name="学生的uuid")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待确认"), ("confirmed", "已确认")],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "sn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="competition.competition",
                        to_field="sn",
                        verbose_name="比赛",
                    ),
                ),
            ],
            options={
                "verbose_name": "成员确认",
                "verbose_name_plural": "成员确认",
                "db_table": "competition_member_confirmation",
            },
        ),
    ]
