# Generated by Django 5.1.2 on 2025-04-12 01:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sn",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=100, verbose_name="比赛名称")),
                ("date", models.DateField(verbose_name="比赛日期")),
                ("description", models.CharField(max_length=1000, verbose_name="比赛描述")),
                ("score", models.CharField(max_length=100, verbose_name="比赛成绩")),
                ("teacher_num", models.IntegerField(default=0, verbose_name="老师数量")),
                (
                    "team_id",
                    models.UUIDField(blank=True, null=True, verbose_name="团队的uuid"),
                ),
                (
                    "file",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="证书图片地址"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "待确认"), ("confirmed", "已确认")],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "比赛",
                "verbose_name_plural": "比赛",
                "db_table": "competition",
            },
        ),
        migrations.CreateModel(
            name="StudentToCompetition",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sn",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "student",
                    models.UUIDField(blank=True, null=True, verbose_name="学生的uuid"),
                ),
                (
                    "team",
                    models.UUIDField(blank=True, null=True, verbose_name="团队的uuid"),
                ),
                ("competition", models.UUIDField(verbose_name="比赛的uuid")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("pending", "待确认"), ("confirmed", "已确认")],
                        default="pending",
                        max_length=20,
                        null=True,
                        verbose_name="状态",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
                ("is_cap", models.BooleanField(default=False, verbose_name="是否是队长")),
            ],
            options={
                "verbose_name": "学生比赛信息表",
                "verbose_name_plural": "学生比赛信息表",
                "db_table": "student_to_competition",
            },
        ),
        migrations.CreateModel(
            name="TeacherToCompetition",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sn",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "teacher",
                    models.UUIDField(blank=True, null=True, verbose_name="老师的uuid"),
                ),
                (
                    "team",
                    models.UUIDField(blank=True, null=True, verbose_name="团队的uuid"),
                ),
                ("competition", models.UUIDField(verbose_name="比赛的uuid")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("pending", "待确认"), ("confirmed", "已确认")],
                        default="pending",
                        max_length=20,
                        null=True,
                        verbose_name="状态",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "老师比赛信息表",
                "verbose_name_plural": "老师比赛信息表",
                "db_table": "teacher_to_competition",
            },
        ),
    ]
