# Generated by Django 5.1.2 on 2025-04-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="teacher",
            field=models.UUIDField(verbose_name="带队老师"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="team_id",
            field=models.UUIDField(verbose_name="团队的uuid"),
        ),
    ]
