# Generated by Django 5.1.2 on 2025-05-11 18:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="competition",
            old_name="team_id",
            new_name="team_sn",
        ),
    ]
