# Generated by Django 5.1.2 on 2025-04-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0002_alter_competition_teacher_alter_competition_team_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
    ]
