# Generated by Django 5.1.2 on 2025-05-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0002_rename_team_id_competition_team_sn"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="reminder_sent",
            field=models.BooleanField(default=False, verbose_name="提醒是否已发送"),
        ),
        migrations.AddField(
            model_name="studenttocompetition",
            name="reminder_sent",
            field=models.BooleanField(default=False, verbose_name="提醒是否已发送"),
        ),
        migrations.AddField(
            model_name="teachertocompetition",
            name="reminder_sent",
            field=models.BooleanField(default=False, verbose_name="提醒是否已发送"),
        ),
    ]
