# Generated by Django 5.1.2 on 2025-04-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0003_competition_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionmemberconfirm",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="备注"),
        ),
    ]
