# Generated by Django 5.1.2 on 2025-04-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0004_competitionmemberconfirm_note"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="competitions/", verbose_name="证书图片"
            ),
        ),
    ]
