# Generated by Django 5.1.2 on 2025-04-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0005_alter_competition_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionmemberconfirm",
            name="student",
            field=models.UUIDField(verbose_name="学生的uuid"),
        ),
    ]
