# Generated by Django 5.1.2 on 2025-04-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0006_alter_competitionmemberconfirm_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="competition",
            name="title",
            field=models.CharField(default=1, max_length=100, verbose_name="比赛名称"),
            preserve_default=False,
        ),
    ]
