# Generated by Django 5.1.2 on 2025-04-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0007_competition_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionmemberconfirm",
            name="sn",
            field=models.UUIDField(verbose_name="比赛的uuid"),
        ),
    ]
