# Generated by Django 5.1.2 on 2025-04-09 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0008_alter_competitionmemberconfirm_sn"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionmemberconfirm",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="创建时间"
            ),
        ),
        migrations.AddField(
            model_name="competitionmemberconfirm",
            name="state",
            field=models.CharField(
                choices=[("1", "正常"), ("0", "停用")],
                default="1",
                max_length=1,
                verbose_name="数据状态",
            ),
        ),
        migrations.AddField(
            model_name="competitionmemberconfirm",
            name="update_time",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
        ),
    ]
