# Generated by Django 5.1.2 on 2025-04-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0009_competitionmemberconfirm_create_time_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competition",
            name="teacher",
        ),
        migrations.AddField(
            model_name="competition",
            name="teacher_num",
            field=models.IntegerField(default=0, verbose_name="老师数量"),
        ),
        migrations.AddField(
            model_name="competitionmemberconfirm",
            name="teacher",
            field=models.UUIDField(blank=True, null=True, verbose_name="带队老师"),
        ),
        migrations.AlterField(
            model_name="competition",
            name="team_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="团队的uuid"),
        ),
        migrations.AlterField(
            model_name="competitionmemberconfirm",
            name="student",
            field=models.UUIDField(blank=True, null=True, verbose_name="学生的uuid"),
        ),
    ]
