# Generated by Django 5.1.2 on 2025-04-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "competition",
            "0010_remove_competition_teacher_competition_teacher_num_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="competitionmemberconfirm",
            name="is_cap",
            field=models.BooleanField(default=False, verbose_name="是否是队长"),
        ),
    ]
