# Generated by Django 5.1.2 on 2025-04-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0011_competitionmemberconfirm_is_cap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitionmemberconfirm",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("pending", "待确认"), ("confirmed", "已确认")],
                default="pending",
                max_length=20,
                null=True,
                verbose_name="状态",
            ),
        ),
    ]
