# Generated by Django 5.1.2 on 2025-04-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0012_alter_competitionmemberconfirm_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="file",
            field=models.CharField(default=1, max_length=255, verbose_name="证书图片地址"),
            preserve_default=False,
        ),
    ]
