# Generated by Django 5.1.2 on 2025-04-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0013_alter_competition_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="description",
            field=models.CharField(max_length=1000, verbose_name="比赛描述"),
        ),
    ]
