# Generated by Django 5.1.2 on 2025-04-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0014_alter_competition_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentToCompetition",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sn", models.UUIDField(verbose_name="比赛的uuid")),
                (
                    "student",
                    models.UUIDField(blank=True, null=True, verbose_name="学生的uuid"),
                ),
                (
                    "team",
                    models.UUIDField(blank=True, null=True, verbose_name="团队的uuid"),
                ),
                ("competition", models.UUIDField(verbose_name="比赛的uuid")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("pending", "待确认"), ("confirmed", "已确认")],
                        default="pending",
                        max_length=20,
                        null=True,
                        verbose_name="状态",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
                ("is_cap", models.BooleanField(default=False, verbose_name="是否是队长")),
            ],
            options={
                "verbose_name": "学生比赛信息表",
                "verbose_name_plural": "学生比赛信息表",
                "db_table": "student_to_competition",
            },
        ),
        migrations.CreateModel(
            name="TeacherToCompetition",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("sn", models.UUIDField(verbose_name="比赛的uuid")),
                (
                    "teacher",
                    models.UUIDField(blank=True, null=True, verbose_name="老师的uuid"),
                ),
                (
                    "team",
                    models.UUIDField(blank=True, null=True, verbose_name="团队的uuid"),
                ),
                ("competition", models.UUIDField(verbose_name="比赛的uuid")),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("pending", "待确认"), ("confirmed", "已确认")],
                        default="pending",
                        max_length=20,
                        null=True,
                        verbose_name="状态",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "老师比赛信息表",
                "verbose_name_plural": "老师比赛信息表",
                "db_table": "teacher_to_competition",
            },
        ),
    ]
