# Generated by Django 5.1.2 on 2025-04-10 21:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0015_studenttocompetition_teachertocompetition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studenttocompetition",
            name="sn",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
