# Generated by Django 5.1.2 on 2025-04-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("competition", "0017_alter_teachertocompetition_sn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="file",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="证书图片地址"
            ),
        ),
    ]
