# Generated by Django 5.1.3 on 2025-04-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="role",
            field=models.CharField(default="student", max_length=32, verbose_name="角色"),
        ),
    ]
