# Generated by Django 5.1.2 on 2025-05-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_usermodel_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="邮箱")),
                ("code", models.CharField(max_length=6, verbose_name="验证码")),
            ],
            options={
                "verbose_name": "短信验证码",
                "verbose_name_plural": "短信验证码",
                "db_table": "sms_code",
            },
        ),
    ]
