# Generated by Django 5.1.2 on 2025-05-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_loginlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginlog",
            name="ip",
            field=models.CharField(max_length=255, verbose_name="IP地址"),
        ),
        migrations.AlterField(
            model_name="loginlog",
            name="location",
            field=models.CharField(max_length=255, verbose_name="位置"),
        ),
    ]
