# Generated by Django 5.1.2 on 2025-05-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_loginlog_ip_alter_loginlog_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="KV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("key", models.CharField(max_length=255, verbose_name="键")),
                ("value", models.TextField(verbose_name="值")),
            ],
            options={
                "verbose_name": "设置表",
                "verbose_name_plural": "设置表",
                "db_table": "kv",
            },
        ),
    ]
