# Generated by Django 5.1.2 on 2025-05-19 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_kv"),
    ]

    operations = [
        migrations.DeleteModel(
            name="KV",
        ),
    ]
