# Generated by Django 5.1.2 on 2025-05-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("username", models.CharField(max_length=255, verbose_name="用户名")),
                ("sn", models.CharField(max_length=255, verbose_name="sn")),
                (
                    "send_email",
                    models.BooleanField(default=True, verbose_name="是否发送邮件"),
                ),
                ("cursor", models.BooleanField(default=True, verbose_name="是否使用系统光标")),
            ],
            options={
                "verbose_name": "用户设置表",
                "verbose_name_plural": "用户设置表",
                "db_table": "settings",
            },
        ),
    ]
