# Generated by Django 5.1.3 on 2025-04-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="College",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="学院名称"),
                ),
                ("prize_num", models.IntegerField(default=0, verbose_name="获奖总数")),
                ("paper_num", models.IntegerField(default=0, verbose_name="论文总数")),
                ("patent_num", models.IntegerField(default=0, verbose_name="专利总数")),
            ],
            options={
                "verbose_name": "成员确认",
                "verbose_name_plural": "成员确认",
                "db_table": "college",
            },
        ),
    ]
