# Generated by Django 5.1.2 on 2025-05-30 23:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inventor",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sn",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("patent", models.UUIDField(verbose_name="专利的uuid")),
                ("name", models.CharField(max_length=50, verbose_name="姓名")),
                ("phone", models.CharField(max_length=20, verbose_name="手机号")),
                ("email", models.CharField(max_length=20, verbose_name="邮箱")),
            ],
            options={
                "verbose_name": "发明人",
                "verbose_name_plural": "发明人",
                "db_table": "patent_inventor",
            },
        ),
        migrations.CreateModel(
            name="Patent",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sn",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("number", models.CharField(max_length=20, verbose_name="专利号")),
                ("name", models.CharField(max_length=100, verbose_name="专利名称")),
                ("date", models.DateField(verbose_name="申请日期")),
                ("description", models.TextField(verbose_name="专利描述")),
                ("patent_type", models.CharField(max_length=20, verbose_name="专利类型")),
                (
                    "applicant_name",
                    models.CharField(max_length=50, verbose_name="申请人姓名"),
                ),
                (
                    "applicant_phone",
                    models.CharField(max_length=20, verbose_name="申请人手机号"),
                ),
                (
                    "applicant_email",
                    models.CharField(max_length=20, verbose_name="申请人电子邮箱"),
                ),
                ("file", models.CharField(max_length=255, verbose_name="证书文件")),
            ],
            options={
                "verbose_name": "专利",
                "verbose_name_plural": "专利",
                "db_table": "patent",
            },
        ),
    ]
