# Generated by Django 5.1.2 on 2025-05-31 01:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patent",
            name="applicant_sn",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
