# Generated by Django 5.1.2 on 2025-05-31 01:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("patent", "0002_patent_applicant_sn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patent",
            name="applicant_sn",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
