# Generated by Django 5.1.2 on 2025-04-11 22:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sn",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("username", models.CharField(max_length=50, verbose_name="姓名")),
                (
                    "gender",
                    models.BooleanField(
                        choices=[(True, "男"), (False, "女")],
                        default=True,
                        verbose_name="性别",
                    ),
                ),
                ("college_id", models.CharField(max_length=100, verbose_name="学院id")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="电话"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="邮箱"),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("professor", "教授"),
                            ("associate_professor", "副教授"),
                            ("lecturer", "讲师"),
                            ("assistant", "助教"),
                        ],
                        max_length=50,
                        verbose_name="职称",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="在职状态")),
            ],
            options={
                "verbose_name": "教师信息",
                "verbose_name_plural": "教师信息",
                "db_table": "teacher",
            },
        ),
    ]
