# Generated by Django 5.1.2 on 2025-05-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="avatar",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="头像"
            ),
        ),
    ]
