# Generated by Django 5.1.3 on 2025-04-07 16:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="name",
            new_name="username",
        ),
    ]
