# Generated by Django 5.1.3 on 2025-04-07 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sn",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100, verbose_name="团队名称")),
                ("race_num", models.IntegerField(default=0, verbose_name="比赛数")),
                ("prize_num", models.IntegerField(default=0, verbose_name="获奖数")),
                ("people_num", models.IntegerField(default=0, verbose_name="人数")),
            ],
            options={
                "verbose_name": "团队",
                "verbose_name_plural": "团队",
                "db_table": "team",
            },
        ),
    ]
