# Generated by Django 5.1.2 on 2025-04-11 22:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudentToTeam",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sn",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("student", models.UUIDField(verbose_name="学生sn")),
                ("team", models.UUIDField(verbose_name="团队sn")),
                ("is_cap", models.BooleanField(default=False, verbose_name="是否是队长")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待接受"),
                            ("accepted", "已接受"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "学生-团队表",
                "verbose_name_plural": "学生-团队表",
                "db_table": "student_to_team",
            },
        ),
        migrations.CreateModel(
            name="TeacherToTeam",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sn",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("teacher", models.UUIDField(verbose_name="老师sn")),
                ("team", models.UUIDField(verbose_name="团队sn")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待接受"),
                            ("accepted", "已接受"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "老师-团队表",
                "verbose_name_plural": "老师-团队表",
                "db_table": "teacher_to_team",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sn",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100, verbose_name="团队名称")),
                ("race_num", models.IntegerField(default=0, verbose_name="比赛数")),
                ("prize_num", models.IntegerField(default=0, verbose_name="获奖数")),
                ("people_num", models.IntegerField(default=0, verbose_name="总人数")),
                ("cap", models.UUIDField(verbose_name="队长sn")),
                ("teacher_num", models.IntegerField(default=0, verbose_name="老师人数")),
            ],
            options={
                "verbose_name": "团队",
                "verbose_name_plural": "团队",
                "db_table": "team",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="TeamInvite",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sn",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "team",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="团队sn"
                    ),
                ),
                (
                    "member_id",
                    models.UUIDField(blank=True, null=True, verbose_name="成员sn"),
                ),
                ("cap", models.UUIDField(verbose_name="队长sn")),
                (
                    "status",
                    models.CharField(
                        choices=[("0", "待接受"), ("1", "已接受"), ("2", "已拒绝")],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "teacher",
                    models.UUIDField(blank=True, null=True, verbose_name="老师sn"),
                ),
            ],
            options={
                "verbose_name": "团队邀请表",
                "verbose_name_plural": "团队邀请表",
                "db_table": "team_invite",
            },
        ),
    ]
