# Generated by Django 5.1.2 on 2025-04-12 01:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeamInvite",
        ),
    ]
