# Generated by Django 5.1.2 on 2025-04-08 08:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamInvite",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sn",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("team_id", models.CharField(max_length=100, verbose_name="团队id")),
                ("member_sn", models.CharField(max_length=100, verbose_name="成员sn")),
                ("cap_sn", models.CharField(max_length=100, verbose_name="队长sn")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待接受"),
                            ("accepted", "已接受"),
                            ("rejected", "已拒绝"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="team",
            name="teacher",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="老师sn"
            ),
        ),
    ]
