# Generated by Django 5.1.2 on 2025-04-08 08:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0002_teaminvite_team_teacher"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teaminvite",
            options={"verbose_name": "团队邀请表", "verbose_name_plural": "团队邀请表"},
        ),
        migrations.AlterModelTable(
            name="teaminvite",
            table="team_invite",
        ),
    ]
