# Generated by Django 5.1.2 on 2025-04-08 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0003_alter_teaminvite_options_alter_teaminvite_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="teaminvite",
            name="teacher_sn",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="老师sn"
            ),
        ),
    ]
