# Generated by Django 5.1.2 on 2025-04-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0004_teaminvite_teacher_sn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teaminvite",
            name="team_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="团队id"
            ),
        ),
    ]
