# Generated by Django 5.1.2 on 2025-05-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0004_alter_teachertoteam_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="status",
            field=models.CharField(
                default="pending", max_length=20, verbose_name="团队状态"
            ),
        ),
    ]
