# Generated by Django 5.1.2 on 2025-05-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0005_team_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="studenttoteam",
            name="reminder_sent",
            field=models.BooleanField(default=False, verbose_name="提醒是否已发送"),
        ),
        migrations.AddField(
            model_name="teachertoteam",
            name="reminder_sent",
            field=models.BooleanField(default=False, verbose_name="提醒是否已发送"),
        ),
        migrations.AddField(
            model_name="team",
            name="reminder_sent",
            field=models.BooleanField(default=False, verbose_name="提醒是否已发送"),
        ),
        migrations.AlterField(
            model_name="studenttoteam",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待接受"),
                    ("confirmed", "已接受"),
                    ("rejected", "已拒绝"),
                    ("expired", "已过期"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AlterField(
            model_name="teachertoteam",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待接受"),
                    ("confirmed", "已接受"),
                    ("rejected", "已拒绝"),
                    ("expired", "已过期"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
