# Generated by Django 5.1.2 on 2025-04-08 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0005_alter_teaminvite_team_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="cap",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=100, verbose_name="队长sn"
            ),
            preserve_default=False,
        ),
    ]
