# Generated by Django 5.1.2 on 2025-04-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0006_team_cap"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teaminvite",
            name="cap_sn",
        ),
        migrations.RemoveField(
            model_name="teaminvite",
            name="member_sn",
        ),
        migrations.RemoveField(
            model_name="teaminvite",
            name="teacher_sn",
        ),
        migrations.AddField(
            model_name="teaminvite",
            name="cap_id",
            field=models.CharField(default=1, max_length=100, verbose_name="队长id"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teaminvite",
            name="member_id",
            field=models.CharField(default=1, max_length=100, verbose_name="成员id"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teaminvite",
            name="teacher_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="老师id"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="cap",
            field=models.CharField(max_length=100, verbose_name="队长id"),
        ),
        migrations.AlterField(
            model_name="team",
            name="teacher",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="老师id"
            ),
        ),
    ]
