# Generated by Django 5.1.2 on 2025-04-08 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0007_remove_teaminvite_cap_sn_remove_teaminvite_member_sn_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teaminvite",
            old_name="cap_id",
            new_name="cap",
        ),
        migrations.RenameField(
            model_name="teaminvite",
            old_name="teacher_id",
            new_name="teacher",
        ),
        migrations.RenameField(
            model_name="teaminvite",
            old_name="team_id",
            new_name="team",
        ),
    ]
