# Generated by Django 5.1.2 on 2025-04-08 18:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0008_rename_cap_id_teaminvite_cap_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentToTeam",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sn",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("student", models.CharField(max_length=100, verbose_name="学生id")),
                ("team", models.CharField(max_length=100, verbose_name="团队id")),
            ],
            options={
                "verbose_name": "学生-团队表",
                "verbose_name_plural": "学生-团队表",
                "db_table": "student_to_team",
            },
        ),
        migrations.CreateModel(
            name="TeacherToTeam",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sn",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("teacher", models.CharField(max_length=100, verbose_name="老师id")),
                ("team", models.CharField(max_length=100, verbose_name="团队id")),
            ],
            options={
                "verbose_name": "老师-团队表",
                "verbose_name_plural": "老师-团队表",
                "db_table": "teacher_to_team",
            },
        ),
        migrations.AlterField(
            model_name="teaminvite",
            name="status",
            field=models.CharField(
                choices=[("0", "待接受"), ("1", "已接受"), ("2", "已拒绝")],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
    ]
