# Generated by Django 5.1.2 on 2025-04-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0009_studenttoteam_teachertoteam_alter_teaminvite_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studenttoteam",
            name="student",
            field=models.CharField(max_length=100, verbose_name="学生sn"),
        ),
        migrations.AlterField(
            model_name="studenttoteam",
            name="team",
            field=models.CharField(max_length=100, verbose_name="团队sn"),
        ),
        migrations.AlterField(
            model_name="teachertoteam",
            name="teacher",
            field=models.CharField(max_length=100, verbose_name="老师sn"),
        ),
        migrations.AlterField(
            model_name="teachertoteam",
            name="team",
            field=models.CharField(max_length=100, verbose_name="团队sn"),
        ),
        migrations.AlterField(
            model_name="team",
            name="cap",
            field=models.CharField(max_length=100, verbose_name="队长sn"),
        ),
        migrations.AlterField(
            model_name="team",
            name="teacher",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="老师sn"
            ),
        ),
        migrations.AlterField(
            model_name="teaminvite",
            name="member_id",
            field=models.CharField(max_length=100, verbose_name="成员sn"),
        ),
        migrations.AlterField(
            model_name="teaminvite",
            name="teacher",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="老师sn"
            ),
        ),
        migrations.AlterField(
            model_name="teaminvite",
            name="team",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="团队sn"
            ),
        ),
    ]
