# Generated by Django 5.1.2 on 2025-04-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0010_alter_studenttoteam_student_alter_studenttoteam_team_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studenttoteam",
            name="student",
            field=models.UUIDField(verbose_name="学生sn"),
        ),
        migrations.AlterField(
            model_name="studenttoteam",
            name="team",
            field=models.UUIDField(verbose_name="团队sn"),
        ),
        migrations.AlterField(
            model_name="teachertoteam",
            name="teacher",
            field=models.UUIDField(verbose_name="老师sn"),
        ),
        migrations.AlterField(
            model_name="teachertoteam",
            name="team",
            field=models.UUIDField(verbose_name="团队sn"),
        ),
        migrations.AlterField(
            model_name="team",
            name="cap",
            field=models.UUIDField(verbose_name="队长sn"),
        ),
        migrations.AlterField(
            model_name="teaminvite",
            name="cap",
            field=models.UUIDField(verbose_name="队长sn"),
        ),
        migrations.AlterField(
            model_name="teaminvite",
            name="member_id",
            field=models.UUIDField(verbose_name="成员sn"),
        ),
        migrations.AlterField(
            model_name="teaminvite",
            name="teacher",
            field=models.UUIDField(blank=True, null=True, verbose_name="老师sn"),
        ),
    ]
