# Generated by Django 5.1.2 on 2025-04-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0011_alter_studenttoteam_student_alter_studenttoteam_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studenttoteam",
            name="is_cap",
            field=models.BooleanField(default=False, verbose_name="是否是队长"),
        ),
    ]
