# Generated by Django 5.1.2 on 2025-04-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0012_studenttoteam_is_cap"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="teacher",
            field=models.UUIDField(blank=True, null=True, verbose_name="老师sn"),
        ),
    ]
