# Generated by Django 5.1.2 on 2025-04-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0013_alter_team_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="team",
            name="teacher",
        ),
        migrations.AddField(
            model_name="team",
            name="teacher_num",
            field=models.IntegerField(default=0, verbose_name="老师人数"),
        ),
        migrations.AlterField(
            model_name="team",
            name="people_num",
            field=models.IntegerField(default=0, verbose_name="总人数"),
        ),
    ]
