# Generated by Django 5.1.2 on 2025-04-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0014_remove_team_teacher_team_teacher_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teaminvite",
            name="member_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="成员sn"),
        ),
    ]
