# Generated by Django 5.1.2 on 2025-04-09 01:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("team", "0015_alter_teaminvite_member_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="team",
            options={
                "ordering": ["-create_time"],
                "verbose_name": "团队",
                "verbose_name_plural": "团队",
            },
        ),
    ]
