# Generated by Django 5.1.2 on 2025-04-11 22:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, null=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[("1", "正常"), ("0", "停用")],
                        default="1",
                        max_length=1,
                        verbose_name="数据状态",
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "sn",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "username",
                    models.CharField(max_length=50, unique=True, verbose_name="姓名"),
                ),
                (
                    "gender",
                    models.BooleanField(
                        choices=[(True, "男"), (False, "女")], verbose_name="性别"
                    ),
                ),
                ("college_id", models.IntegerField(verbose_name="学院id")),
                ("cn", models.CharField(max_length=250, verbose_name="身份证")),
                ("phone", models.CharField(max_length=20, verbose_name="电话")),
                ("prize_num", models.IntegerField(default=0, verbose_name="获奖总数")),
                ("race_num", models.IntegerField(default=0, verbose_name="比赛总数")),
                (
                    "email",
                    models.CharField(blank=True, max_length=100, verbose_name="邮箱"),
                ),
                (
                    "avatar",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="头像"
                    ),
                ),
            ],
            options={
                "verbose_name": "学生",
                "verbose_name_plural": "学生",
                "db_table": "student",
            },
        ),
    ]
