# Generated by Django 5.1.3 on 2025-04-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.CharField(blank=True, max_length=100, verbose_name="邮箱"),
        ),
    ]
