# Generated by Django 5.1.2 on 2025-05-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="note",
            field=models.CharField(blank=True, max_length=255, verbose_name="备注"),
        ),
    ]
