# Generated by Django 5.1.3 on 2025-04-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_student_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="cn",
            field=models.CharField(max_length=100, unique=True, verbose_name="身份证"),
        ),
    ]
