# Generated by Django 5.1.2 on 2025-05-19 05:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_student_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="send_email",
            field=models.BooleanField(default=True, verbose_name="是否发送邮件"),
        ),
    ]
