# Generated by Django 5.1.2 on 2025-05-19 18:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_student_send_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="send_email",
        ),
    ]
