# Generated by Django 5.1.3 on 2025-04-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_alter_student_cn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="cn",
            field=models.CharField(max_length=250, unique=True, verbose_name="身份证"),
        ),
    ]
