# Generated by Django 5.1.2 on 2025-04-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0004_alter_student_cn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="cn",
            field=models.CharField(max_length=250, verbose_name="身份证"),
        ),
    ]
