# Generated by Django 5.1.2 on 2025-04-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0005_alter_student_cn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="is_cap",
            field=models.BooleanField(default=False, verbose_name="是否是队长"),
        ),
    ]
