# Generated by Django 5.1.2 on 2025-04-08 18:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0006_alter_student_is_cap"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="team_id",
        ),
    ]
