# Generated by Django 5.1.2 on 2025-04-08 20:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0007_remove_student_team_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="is_cap",
        ),
    ]
