# Generated by Django 5.1.2 on 2025-04-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0008_remove_student_is_cap"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="avatar",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="头像"
            ),
        ),
    ]
